# Generated by Django 4.2.1 on 2023-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('hiring_manager', models.CharField(blank=True, max_length=100)),
                ('introduction', models.TextField()),
                ('skills_and_qualifications', models.TextField()),
                ('achievements', models.TextField()),
                ('motivation', models.TextField()),
                ('closing', models.TextField()),
            ],
        ),
    ]
